### PR TITLE
Folder Structure

### PR DESCRIPTION
**Pull request by rushsteve1**
I put everything in the standard Cargo folder structure, added a .travis.yml, and made a few little cleanup fixes.

### CODE REVIEW

**Comment by ticki** [comment]
You commited /target :wink:

**Comment by rushsteve1** [comment]
Sorry about that, completely forgot about it. It's all fixed now @ticki, thanks for reminding me.

**Comment by ticki** [comment]
Could you rebase it all together.

**Comment by rushsteve1** [comment]
I'm fairly new to the more advanced features of Git like rebasing, and I kinda made a mess of this, so I'm just gonna close this and open a new pull request without all the craziness.

**Pull request closed without merging**
